### ISSUE TITLE
ignoreEmptyRow(true), 忽略末尾空白行无效

### ISSUE THREAD

**Issue by fengyts** [alibaba/easyexcel#4036] opened 2024-10-27 15:37 UTC
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
忽略末尾空白行无效。
附件信息：
[test.xlsx](https://github.com/user-attachments/files/17534477/test.xlsx)

# 触发Bug的代码
```java
@Test
    public void testIgnoreEmptyRow(){
        File file = new File("E:\\test\\test.xlsx");

        List<Object> objects = EasyExcel.read(file).ignoreEmptyRow(true).doReadAllSync();
        System.out.println();
    }
```
# 提示的异常或者没有达到的效果
没有报错，但是末尾行没有忽略空白行。
版本信息：EasyExcel版本：3.0.5，poi: 4.1.2, poi-ooxml: 4.1.2
![image](https://github.com/user-attachments/assets/d694c436-fe8d-4f3f-92fc-6ab50dd7ba12)

**Comment by psxjoy** [comment] 2024-10-28 02:07
It's not a bug.
Even if you see all sheets are empty, when you open this file using unzip, you will find these(you think are empty) cells have some style config, which can be considered real data without the real info（such as number or string） but truly a useful cell.

**Comment by nltheme** [comment] 2024-10-28 15:03
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by psxjoy** [comment] 2024-12-13 08:59
This issue has been completed, I will close this issue.

**Closed by psxjoy** 2024-12-13 08:59 UTC
Labels: help wanted
