### ISSUE TITLE
application builds failed under native-image

### ISSUE THREAD

**Issue by imgoby** [alibaba/easyexcel#3994] opened 2024-09-15 13:48 UTC
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
[   这里写你的代码](https://github.com/imgoby/spring-native-easyexcel)
```
# 异常提示
========================================================================================================================
Failed generating 'spring-native-easyexcel' after 7.4s.

The build process encountered an unexpected error:

> com.oracle.svm.core.util.VMError$HostedError: Cannot define class com.alibaba.excel.support.cglib.beans.BeanMap$Generator$BeanMapKey$$KeyFactoryByCGLIB$$4a680349 from byte[0..1386] using class loader: jdk.internal.loader.Loader@4cc0edeb

Please inspect the generated error report at:
/root/spring-native-easyexcel/target/svm_err_b_20240915T200908.080_pid30101.md

# 问题描述

**Comment by psxjoy** [comment] 2024-09-15 16:55
I don't believe this is an EasyExcel issue. I couldn't reproduce the problem using the demo you provided. In my opinion, this might be related to the JDK version. I suggest trying OpenJDK or a different JDK version.
我并不认为这是easyexcel的问题。我无法根据你提供的demo复现对应的问题。我个人认为是JDK版本的问题，建议使用openJDK或者是其他版本的JDK。



<img width="376" alt="image" src="https://github.com/user-attachments/assets/5bf7ccfb-dfb4-4a15-b9fd-40de0e010e33">

**Comment by imgoby** [comment] 2024-09-15 23:12
Does EasyExcel support native image?

**Comment by imgoby** [comment] 2024-09-15 23:18
Step in Centos OS:
1. install jdk and native-image
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install java 22.3.r17-nik
sdk use java 22.3.r17-nik

3. mvn clean package
4. java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image/,experimental-class-define-support --enable-preview -jar target/spring-native-easyexcel-1.0-SNAPSHOT.jar
5. mvn -P native native:compile
 the error will be found.

**Comment by psxjoy** [comment] 2024-09-15 23:24
I think We don't support native-image now, for the easyexcel using cglib as a tool to generate class. I remember some other people has already made issues about easyexcel not support in GraalVM.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 小虾虎鱼 ***@***.***>
发送时间: Monday, September 16, 2024 7:18:49 AM
收件人: alibaba/easyexcel ***@***.***>
抄送: psxjoy ***@***.***>; Assign ***@***.***>
主题: Re: [alibaba/easyexcel] application builds failed under native-image (Issue #3994)


Step in Centos OS:

  1.  install jdk and native-image
curl -s "https://get.sdkman.io<https://get.sdkman.io/>" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install java 22.3.r17-nik
sdk use java 22.3.r17-nik

  1.  mvn clean package
  2.  java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image/,experimental-class-define-support --enable-preview -jar target/spring-native-easyexcel-1.0-SNAPSHOT.jar
  3.  mvn -P native native:compile
the error will be found.

―

**Comment by imgoby** [comment] 2024-09-18 08:14
I understand, we need to remove the dependency on cglib in easyxcel support in order to resolve it. I just need to modify the code and use fastjson 2
Old code:
(1) Add MyBeanMap
```
public class MyBeanMap extends HashMap {
private Object bean;
﻿
public Object getBean() {
return bean;
}
﻿
public void setBean(Object bean) {
this.bean = bean;
}
}
```
(2) Add reference:
```
<dependency>
<groupId>com.alibaba.fastjson2</groupId>
<artifactId>fastjson2</artifactId>
</dependency>
```
(3) Modify code:
`BeanMap dataMap = BeanMapUtils.create(resultModel);`
For:
```
String jsonStr = JSON.toJSONString(resultModel);
MyBeanMap dataMap = JSON.parseObject(jsonStr, MyBeanMap.class);
dataMap.setBean(resultModel);
```

**Comment by psxjoy** [comment] 2024-09-29 01:35
I see this issue has been linked to another issue URL. I think this issue has been resolved, I will close this issue.

**Closed by psxjoy** 2024-09-29 01:35 UTC
Labels: help wanted
